version: "3.0"

networks:
  default:  # 自定义网络
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
  default2: # 使用外部网络algo-net  true: 如果外部网络不存在则提示错误   false: 外部网络不存在则自动创建名称为algo-net的网络
    external: true
    name: algo-net


services:
  trace_dev:
    image: "trace:${TAG:-1.0.0}"
    build:
      context: ./ 
      dockerfile: Dockerfile
    restart: always
    container_name: "trace_dev"
    volumes:
      - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
      - ../../dt_resource/trace_dev/logs:/usr/src/app/logs
    ports:
      - 18075:18072
    environment:
      TZ: "Asia/Shanghai"
      ENV: 'dev'
    networks:
      - default

  trace_test:
    image: "trace:${TAG:-1.0.0}"
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: "trace_test"
    volumes:
      - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
      - ../../dt_resource/trace_test/logs:/usr/src/app/logs
    ports:
      - 18077:18072
    environment:
      TZ: "Asia/Shanghai"
      ENV: 'test'
    networks:
      default2:
        ipv4_address: 172.30.0.11
