# test config
postgresql:
  host: 192.168.30.51
  port: 35432
  user: postgres
  password: 123456
  db_name: alpha_slsl_dt_core
  type: com.zaxxer.hikari.HikariDataSource

tdengine:
  host: 192.168.30.51
  port: 2041
  user: root
  password: "taosdata"
  db_name: slsl_dt_v2
